[package]
name = "evol2d"
version = "0.1.0"
authors = ["Jarod duret <jarod8405@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.2"
toml = "0.5.0"

gfx_core = "0.8.3"
gfx_device_gl = "0.15.3"

imgui = "0.0.22"
imgui-gfx-renderer = "0.0.22"